#!/usr/bin/env escript

main([FileName]) ->
    case file:consult(FileName) of
        {ok, [Config]}  -> DiscoVal = proplists:get_value(disco, Config),
                           NodeVals = proplists:get_value(workers, DiscoVal),
                           lists:map(fun({_GroupName, IP, _RankingGroup}) ->
                                             io:format("~s~n", [IP])
                                     end, NodeVals);
        {error, Reason} -> io:format("Error reading ~s: ~p~n", [FileName, Reason]);
        _               -> io:format("Unknown error~n")
    end;
main(_) ->
    io:format("Read IPs from given config file.~n"),
    io:format("  Format:~n"),
    io:format("  get_ips_from_config CONFIG_FILE~n").
