name: Main CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['23', '25']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: Compile
        run: make compile
      - name: Typecheck
        run: make dialyze
      - name: Run Unit Tests
        run: make eunit_test
      - name: Run Integration Tests
        run: make integration_test
